//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public applicants()
        {
            this.resume_tab = new HashSet<resume_tab>();
        }
    
        public long ID_applicant { get; set; }
        public string lastname_applicant { get; set; }
        public string name_applicant { get; set; }
        public string middlename_applicant { get; set; }
        public string number_phone_app { get; set; }
        public string email_app { get; set; }
        public System.DateTime birthday_app { get; set; }
        public string gender_app { get; set; }
        public string address_app { get; set; }
        public Nullable<long> ID_resume { get; set; }
        public long ID_user { get; set; }
        public byte[] imageData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resume_tab> resume_tab { get; set; }
        public virtual users users { get; set; }
    }
}
