//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class employers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employers()
        {
            this.vacancy = new HashSet<vacancy>();
        }
    
        public long ID_employee { get; set; }
        public string name_employee { get; set; }
        public string number_phone_emp { get; set; }
        public Nullable<int> ID_company { get; set; }
        public string address_employee { get; set; }
        public long ID_user { get; set; }
    
        public virtual companyMany companyMany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vacancy> vacancy { get; set; }
        public virtual users users { get; set; }
    }
}
