//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacancy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecruitmentAgencyEntities : DbContext
    {
        public RecruitmentAgencyEntities()
            : base("name=RecruitmentAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<applicant> applicants { get; set; }
        public virtual DbSet<competency> competencies { get; set; }
        public virtual DbSet<employer> employers { get; set; }
        public virtual DbSet<respons> responses { get; set; }
        public virtual DbSet<resume_tab> resume_tab { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<types_users> types_users { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vacancy> vacancies { get; set; }
    }
}
