//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class resume_tab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resume_tab()
        {
            this.responses = new HashSet<respons>();
        }
    
        public long ID_resume { get; set; }
        public long ID_applicant { get; set; }
        public string skills { get; set; }
        public string req_position { get; set; }
        public long ID_comp { get; set; }
        public Nullable<decimal> req_salary { get; set; }
    
        public virtual applicant applicant { get; set; }
        public virtual competency competency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respons> responses { get; set; }
    }
}
