//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancyView
    {
        public long ID_employee { get; set; }
        public string post { get; set; }
        public decimal salary { get; set; }
        public string name_employee { get; set; }
        public string number_phone_emp { get; set; }
        public string name_company { get; set; }
        public string address_company { get; set; }
        public string phone_company { get; set; }
        public string title_company { get; set; }
        public string competencies { get; set; }
        public string address_employee { get; set; }
    }
}
